### ISSUE TITLE
Allow passing in event field name=value pairs via --env

### ISSUE THREAD

**Issue by otisg** [sematext/sematext-agent-docker#20] opened 2016-11-16 20:41 UTC
I'd like to run Sematext Docker Agent so that it always includes certain tags as fields in all logs it collects.  I'd like to be able to do something like this:

Docker Daemon settings:
```dockerd --label environment=PROD --log-driver=json-file --log-opt env=com.example.service,com.example.environment```

Example service create:
```docker service create --constraint engine.labels.environment==PROD --replicas 2 --name hw --env "com.example.service=FOO" --env "com.example.environment=PROD" alpine ping docker.com```

This would then create log entries with field com.example.service with a value of FOO and com.example.environment with a value of PROD.

**Comment by megastef** [comment] 2016-11-18 00:44
A list of labels/env vars should be specified with 
`docker run -e TAGGING_LABELS='environment,com.example.environment'  ... sematext/sematext-agent-docker:dev`

Wildcards are supported  `TAGGING_LABELS='*example*'`. 

Image for tests: `sematext/sematext-agent-docker:dev`

![bildschirmfoto 2016-11-18 um 01 30 58](https://cloud.githubusercontent.com/assets/7289505/20414013/63834040-ad30-11e6-8012-4a79dc07f67c.png)

**Comment by randomxxxx** [comment] 2016-11-18 17:41
I can't seem to get this to work.  I started the Sematext agent using:
docker service create --mode global --name sematext-agent-docker --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock -e SPM_TOKEN=<token> -e LOGSENE_TOKEN=<token> -e TAGGING_LABELS='com.service,com.environment' sematext/sematext-agent-docker

I then create a service using this:
docker service create --replicas 10 --name hw --label "com.service=testservice" --label "com.environment=dev" alpine ping docker.com

I am not seeing anything in the logs:
![sematext](https://cloud.githubusercontent.com/assets/14948231/20439967/d7a9b124-ad72-11e6-9ce4-ac3d0ac7884a.jpg)

I should see two additional fields, com.service with a value of testservice and com.environment with a value of dev.  Thanks for your help!

**Comment by megastef** [comment] 2016-11-18 19:21
This feature is only released in the `:dev` image. 
Please try: 

```
docker service create --mode global --name sematext-agent-docker \
--mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
-e SPM_TOKEN=$YOUR_SPM_TOKEN -e LOGSENE_TOKEN=$YOUR_LOGSENE_TOKEN \
-e TAGGING_LABELS='com.service,com.environment' \
sematext/sematext-agent-docker:dev
```

**Comment by randomxxxx** [comment] 2016-11-18 20:32
Still no luck...

I start Sematext using this:
docker service create --mode global --name sematext-agent-docker --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock -e SPM_TOKEN=<token> -e LOGSENE_TOKEN=<token> -e TAGGING_LABELS='com.service,com.environment' sematext/sematext-agent-docker:dev

I start the service using:
docker service create --replicas 10 --name hw --label "com.stn.service=testservice" --label "com.stn.environment=devenv" alpine ping docker.com

And my logs look like this:
![sematext](https://cloud.githubusercontent.com/assets/14948231/20445682/dc527bb2-ad8a-11e6-8a4a-5fd3431bbc59.jpg)

I also deleted all docker images just to ensure I got the latest one for :dev.

I appreciate the help!

**Comment by megastef** [comment] 2016-11-18 22:56
Sorry, I think it worked only for Env vars. 
Please run `docker pull sematext/sematext-agent-docker:dev` and try again. 
Here is the result of my test: 

![bildschirmfoto 2016-11-18 um 23 50 59](https://cloud.githubusercontent.com/assets/7289505/20449521/2d6aae48-adea-11e6-8249-ff218a3dc870.png)

We will make a change to support dots in the label name (related to Elasticsearch settings) and add host Labels (not ready in this version).

BTW, you used different Labels than defined in TAGGING_LABELS:
com.stn.environment -> TAGGING_LABELS="com.*.environment"

**Comment by randomxxxx** [comment] 2016-11-21 21:58
Sounds good, look forward to future changes. I did get things working by using env variables - thanks for your help!

**Comment by otisg** [comment] 2016-11-21 22:10
Awesome.  We'll be rolling that into the master soon, thanks for the feedback!

**Comment by otisg** [comment] 2016-11-29 01:56
I believe this is now in the "latest" and can be closed, right @megastef ?

**Comment by megastef** [comment] 2016-11-29 07:04
Yes. The issue is still open, because one commit for the collection of host labels is still missing.

**Comment by megastef** [comment] 2016-11-29 19:56
Closing. 

Finally TAGGING_LABELS apply to docker daemon labels and container labels in SDA >v1.31.3 (latest). 
Example: 
Running docker daemon with this options: 
```
DOCKER_OPTS='-H unix:///var/run/docker.sock --storage-driver aufs --label provider=scaleway --mtu=1500'
```

and sematext-docker-agent with option -e TAGGING_LABELS='provider' would attach ```label.provider: scaleway``` to every log event. 

![bildschirmfoto 2016-11-29 um 18 34 49](https://cloud.githubusercontent.com/assets/7289505/20726458/026a5d30-b676-11e6-83af-47bc88932d56.png)
I used -e TAGGING_LABELS='*' in the example above, so the Redis container is tagged with all env. variables and all labels.

**Closed as completed by megastef** 2016-11-29 19:56 UTC

**Comment by megastef** [comment] 2016-11-30 08:21
Labels set to docker daemon and collected via TAGGING_LABELS filter are visible in SPM as "Host" tags. See screenshot:
![bildschirmfoto 2016-11-30 um 09 18 52](https://cloud.githubusercontent.com/assets/7289505/20744801/4234c366-b6de-11e6-8382-4e867d5e79c8.png)
