### ISSUE TITLE
JSON logs are sometimes not recognized

### ISSUE THREAD

**Issue by otisg** [sematext/sematext-agent-docker#12] opened 2016-07-26 20:55 UTC
Reported by @rocketraman via https://groups.google.com/d/msg/sematext-docker-agent/k_CQIEqAALM/xRvcCzOdBwAJ

**Comment by rocketraman** [comment] 2016-07-27 16:57
Any progress on this? Thx

**Comment by megastef** [comment] 2016-07-27 17:08
Yes. I think its related to handling of multi-line parsers. Fix in work (detect JSON before multi-line processor). I did not check but a pattern with blockStart: /^{.*}$/  for the specific JSON log source - could be a workaround.

**Comment by rocketraman** [comment] 2016-07-27 17:19
Or perhaps even `/^\{/` would be sufficient, given I know the log source produces json. If you think the fix will be in soon (within a day or so) I'll just wait, otherwise I'll look into the pattern workaround.

**Comment by megastef** [comment] 2016-07-27 19:23
[Logagent-js 1.x](https://github.com/sematext/logagent-js/tree/1.x) got a fix and tested on stdin (JSON in / YAML out): 

```
echo '{"x":1}
 {"x":2}
 {"x":3}
 {"x":4}
 {"x":5}' | bin/logagent.js --yaml
```

Output in YAML format: 

```
{"x":1}
x:          1
@timestamp: Wed Jul 27 2016 21:08:53 GMT+0200 (CEST)

{"x":2}
x:          2
@timestamp: Wed Jul 27 2016 21:08:53 GMT+0200 (CEST)

2016-07-27T19:08:53.893Z terminate reason: undefined
{"x":3}
x:          3
@timestamp: Wed Jul 27 2016 21:08:53 GMT+0200 (CEST)

{"x":4}
x:          4
@timestamp: Wed Jul 27 2016 21:08:53 GMT+0200 (CEST)

{"x":5}
x:          5
@timestamp: Wed Jul 27 2016 21:08:53 GMT+0200 (CEST)
```

So it outputs a message object in YAML format for each JSON line. In Docker agent, this should lead to a log message in Logsene for each JSON line. 

@rocketraman Because we have no details about your data please use this image `sematext/sematext-agent-docker:dev` to test LD-JSON log output from Docker containers.  
We will also use it for tests (tomorrow).

**Comment by rocketraman** [comment] 2016-07-27 20:11
@megastef  I just tried the `:dev` image, and it is not working properly. I see this notification from docker cloud:

```
sematext-agent-docker-2: Container stopped with exit code 2
2016-07-27T20:06:24.956883980Z     at processImmediate [as _immediateCallback] (timers.js:523:5) 
```

Every log message causes the container to die and restart.

**Comment by rocketraman** [comment] 2016-07-27 20:17
I got more information from the container logs -- seems to be an issue processing the `@timestamp` field in my logs:

```
sematext-agent-docker-2 | 2016-07-27T20:14:43.291419270Z   TypeError: logObject.@timestamp.getTime is not a function
sematext-agent-docker-2 | 2016-07-27T20:14:43.291428880Z     at Object.DockerLogsene.enrichAndLog (/usr/lib/node_modules/sematext-agent-docker/lib/dockerLogsene.js:278:47)
sematext-agent-docker-2 | 2016-07-27T20:14:43.291435915Z     at /usr/lib/node_modules/sematext-agent-docker/lib/dockerLogsene.js:204:14
sematext-agent-docker-2 | 2016-07-27T20:14:43.291442709Z     at Object.LogParser.parseLine (/usr/lib/node_modules/sematext-agent-docker/node_modules/logagent-js/lib/index.js:367:11)
sematext-agent-docker-2 | 2016-07-27T20:14:43.291449560Z     at DockerLogsene.getLogObject (/usr/lib/node_modules/sematext-agent-docker/lib/dockerLogsene.js:202:19)
sematext-agent-docker-2 | 2016-07-27T20:14:43.291456325Z     at Immediate._onImmediate (/usr/lib/node_modules/sematext-agent-docker/lib/dockerLogsene.js:296:10)
sematext-agent-docker-2 | 2016-07-27T20:14:43.291462962Z     at tryOnImmediate (timers.js:543:15)
sematext-agent-docker-2 | 2016-07-27T20:14:43.291469432Z     at processImmediate [as _immediateCallback] (timers.js:523:5)
sematext-agent-docker-2 | 2016-07-27T20:14:43.296348047Z {"@timestamp":"2016-07-27T20:14:43.269+00:00","@version":1,"message":"This is a test message.","logger_name":"FooCategory","thread_name":"XNIO-2 task-7","level":"DEBUG","level_value":10000,"HOSTNAME":"backend-1"}
```

**Comment by megastef** [comment] 2016-07-27 20:44
Thx for reporting. Going to fix. The problem is that the timestamp needs to be converted to a JavaScript date object. The agent crashed here, because it tries to call a date function on a string.

**Comment by rocketraman** [comment] 2016-07-27 20:57
What is the right way for my logs to put the `timestamp` in? I see this chunk of code:

https://github.com/sematext/logagent-js/blob/master/lib/index.js#L375

I am using https://github.com/logstash/logstash-logback-encoder. By default this encoder uses the Logstash json format (see https://github.com/logstash/logstash-logback-encoder#standard-fields) with `@timestamp` but I can configure it with whatever fields I want. However I don't see any way with the current logagent-js code on github to pass my time field correctly.

Maybe an explicit entry is needed for logstash json just like the Python Eliot one?

**Comment by megastef** [comment] 2016-07-27 21:16
The date format is fine, and can be parsed by Node.js Date() function. Anyhow we have to think about handling various date formats in JSON fields (e.g. parsing with moment-js and special pattern definitions to convert JSON objects). Currently you could define some conversion in patterns.yml with the globalTransform function.  

Patch is on its way ... https://github.com/sematext/logagent-js/commit/5b8e017580c11a411ee879418d2bb0422bb5597c

**Comment by rocketraman** [comment] 2016-07-27 21:23
I think that change is going to ignore my timestamp value and replace it with `new Date()` at line 346 because the `if` at line 322 only allows the timestamp parsing to proceed if `@timestamp` does not already exist:

https://github.com/sematext/logagent-js/commit/5b8e017580c11a411ee879418d2bb0422bb5597c#diff-6d186b954a58d5bb740f73d84fe39073R332

**Comment by rocketraman** [comment] 2016-07-27 21:25
Also your changes at line 334 and 336 seem unnecessary because you have checked your values are already `Date` objects.

**Comment by megastef** [comment] 2016-07-27 21:51
Thanks for the input. Line 332 is to look for alternative timestamp fields. In 344 condition to overwrite was wrong. 
https://github.com/sematext/logagent-js/commit/3361aa02db9cda2a53fe2e3f8c50edc7787cc985

Feel free to make a PR to logagent-js, but keep in mind it should return an object with valid @timestamp. 

I made a quick run with the new `sematext/sematext-agent-docker:dev` image, and it works fine with Kibana Logs.  I did also check your example in logagent (note my timezone is CEST): 

```
{"@timestamp":"2016-07-27T20:14:43.269+00:00","@version":1,"message":"This is a test message.","logger_name":"FooCategory","thread_name":"XNIO-2 task-7","level":"DEBUG","level_value":10000,"HOSTNAME":"backend-1"}
@timestamp:  Wed Jul 27 2016 22:14:43 GMT+0200 (CEST)
@version:    1
message:     This is a test message.
logger_name: FooCategory
thread_name: XNIO-2 task-7
level:       DEBUG
level_value: 10000
HOSTNAME:    backend-1
```

**Comment by rocketraman** [comment] 2016-07-27 21:57
Excellent, with your latest changes it should work perfectly. Are these changes available in `sematext/sematext-agent-docker:dev` already?

**Comment by megastef** [comment] 2016-07-27 22:06
Yes. Please pull the image again.

**Comment by megastef** [comment] 2016-07-27 22:08
Funny, I wrote we will test tomorrow. It is midnight here in Germany :)

**Comment by rocketraman** [comment] 2016-07-27 22:18
Some good news before you go to bed: it worked perfectly! Thx for staying up late :-)

**Comment by rocketraman** [comment] 2016-07-27 22:35
Hmm well the json parsing is working but a different issue now with the dev container: I'm getting many many duplicate logs in logsene -- on the order of thousands. The source container is the agent container, and it is sending the same log repeatedly.

**Comment by megastef** [comment] 2016-07-28 19:08
Ok. Please try again with the :dev image. Ping: @rocketraman

**Comment by rocketraman** [comment] 2016-07-28 19:37
@megastef  Not getting any logging output at all from :dev, except for some logs shipped counts from the agent itself.

**Comment by megastef** [comment] 2016-07-28 19:39
Sorry, the right build just finished. https://hub.docker.com/r/sematext/sematext-agent-docker/builds/

**Comment by rocketraman** [comment] 2016-07-28 19:40
Redeploying now...

**Comment by megastef** [comment] 2016-07-28 19:41
Works for my Kibana JSON logs (bunyan format). 

![bildschirmfoto 2016-07-28 um 21 40 33](https://cloud.githubusercontent.com/assets/7289505/17226881/fc14ca04-550b-11e6-9412-102f2d95db11.png)

**Comment by rocketraman** [comment] 2016-07-28 19:43
Nope, still nothing:

![lot1](https://cloud.githubusercontent.com/assets/53049/17226970/0e7f4f34-54da-11e6-91f7-936e7f08c098.png)

**Comment by megastef** [comment] 2016-07-28 19:45
Please add -e SKIP_BY_IMAGE=sematext-agent-docker

```
docker run -d --name sematext-agent --restart=always -e SPM_TOKEN=MY_SPM_TOKEN -e LOGSENE_TOKEN=MY_LOGSENE_TOKEN -e SKIP_BY_IMAGE=sematext-agent-docker -v /var/run/docker.sock:/var/run/docker.sock sematext/sematext-agent-docker:dev
```

Thats related to another problem, I'm fighting with because of changes in docker-loghose.

**Comment by rocketraman** [comment] 2016-07-28 19:53
Yup, its working now! The json is parsed correctly, and the timestamp is good too. So far so good.

**Comment by megastef** [comment] 2016-07-28 19:56
Thanks for the feedback, it will take a few more days for a new release.

**Comment by rocketraman** [comment] 2016-07-28 19:59
No problem, I'll stay on dev for now. Thanks a lot for fixing this up.

**Comment by megastef** [comment] 2016-08-04 15:03
The "latest" Image (1.30.15) should be updated to support your JSON logs

**Comment by rocketraman** [comment] 2016-08-04 15:18
Excellent, will give it a shot. Would like to help resolve issue #13 first though -- just in case a redeploy masks the problem.

**Comment by rocketraman** [comment] 2016-08-04 20:41
Now running 1.30.16 and everything works fine. Thanks!

**Closed as completed** 2016-08-04 20:44 UTC
